name: Node.js Pipeline

on:
  push: 
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    uses: ./.github/workflows/test.yaml

  scan:
    needs: test
    uses: ./.github/workflows/scan.yaml
    secrets: inherit

  deploy:
    needs: scan
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit

  validate-deploy:
    needs: deploy
    uses: ./.github/workflows/validate.yaml
    secrets: inherit

  