name: Scan

on:
 workflow-call:
  branch: ["main"]

jobs:
  Sonarqube:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello World"
  Security:
    runs-on: ubuntu-latest
    steps:
    - run: echo "GoodBye World"