name: Scan

on:
 workflow_call:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    environment: Standard
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@5.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
  Security:
    runs-on: ubuntu-latest
    steps:
    - run: echo "GoodBye World"